-- CreateEnum
CREATE TYPE "CVStatus" AS ENUM ('CREATED', 'ANALYZED', 'REVISED', 'PUBLISHED', 'ARCHIVED', 'COMPLETED');

-- AlterTable
ALTER TABLE "cv" ADD COLUMN     "status" "CVStatus" NOT NULL DEFAULT 'CREATED';
